Hw1
rudney5000/2024-2-VK-EDU-Frontend-N-Dedy pull request #1
Opened 2024-09-19 09:27 UTC by rudney5000

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir  проверить его.

Что было сделано:
* Реализованы функции convertBytesToHuman, correctSentence, nonUniqueElements
* Добавлены тесты для функции convertBytesToHuman

2024-09-21 12:37 UTC, Ivan-Bir requested changes

2024-09-21 12:37 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +/*
Привет! Добро пожаловать на курс
Я буду твоим ментором и буду рад ответить на любые вопросы по курсу

2024-09-21 12:37 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +const isValidNumber = value => typeof value === 'number' && !Number.isNaN(value) && value >= 0;
1. Давай будем придерживаться общего стиля, если раньше использовал function, то почему и здесь так не сделать, либо наоборот везде использовать молодежные стрелочные функции
2. Проверка !Number.isNaN(value) включена в value >= 0, поэтому лишняя
3. Параметр стрелочной функции принято оборачивать в скобки, даже если он один

2024-09-21 12:37 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +function round(value, digits){
Нет пробел перед фигурной скобкой. Чтобы не отвлекаться помарки форматирования можно установить для vscode расширение Prettier

2024-09-21 12:37 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  // your solution goes here
Лишний коммент

2024-09-21 12:37 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  const NAMES_OF_UNIT = ["B", "KB", "MB", "GB", "TB"];
1. Петабайт тоже возможен, давай и его обработаем
2. Такие константы обычно выносят наверх файла или в какое-нибудь общее для проекта место, типа constants.ts. Здесь и далее

2024-09-21 12:37 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman("23")).not.toBe("23 B")
Лишняя на мой взгляд проверка. Эта и выше
Не увидел проверки на дробные числа и NaN

2024-09-21 12:37 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +test('Возвращает false для неправильного типа данных', () => {
Начинают обычно с позитивных кейсов. Так чуть проще воспринимать код теста сверху вниз

2024-09-21 12:37 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(1024)).toBe("1 KB")
1023 и 1025 тоже относится к граничным случаям, давай покроем

2024-09-21 12:37 UTC, Ivan-Bir commented on correctSentence.js
> +  // return `${text}.`;
Лишние коменты

2024-09-21 12:37 UTC, Ivan-Bir commented on correctSentence.js
> +  return `${text.charAt(0).toUpperCase()}${text.slice(1)}${text.charAt(text.length - 1) === '.'? '': '.'}`;
Где-то я это уже видел...

2024-09-21 12:37 UTC, Ivan-Bir commented on correctSentence.js
> +  // your solution goes here
Не помешает проверка на !text хотя бы. Это может выручить даже, если мы "уверены", что на вход придет строка. Если сюда попадет undefined, то код выполнится с ошибкой, а это фатально на продакшене

2024-09-21 12:37 UTC, Ivan-Bir commented on correctSentence.test.js
> +test('returns correct sentence', () => {
Нет проверок граничных случаев, например пустой строки

2024-09-21 12:37 UTC, Ivan-Bir commented on nonUniqueElements.js
> +  // your solution goes here
Лишний комент

2024-09-21 12:37 UTC, Ivan-Bir commented on nonUniqueElements.js
> +  // Count occurrences of each element
Это можно не пояснять. Для таких маленьких функций название должно почти полностью отражать их работу, либо есть совсем неочевидные места

2024-09-21 12:37 UTC, Ivan-Bir commented on nonUniqueElements.js
> +  return data.filter(el => countMap.get(el) > 1);
Давай попробуем найти решение за один обход массива

2024-09-21 12:37 UTC, Ivan-Bir commented on nonUniqueElements.test.js
> +  expect(nonUniqueElements([10, 9, 10, 10, 9, 8])).toEqual([10, 9, 10, 10, 9]);
Можно и от себя парочку тесткейсов написать

2024-09-21 12:37 UTC, Ivan-Bir commented on package.json
> +}
Не забываем оставлять пустую строку в конце файла. Это помогает избегать конфликтов гита при мерже

2024-09-21 12:37 UTC, Ivan-Bir commented on nonUniqueElements.js
> +  for(let i = 0; i < data.length; i++){
Ух, давай вместо сишного синтаксиса пользоваться молодежными методами работы с массивами в js

2024-09-23 13:48 UTC, rudney5000 commented
Прошу @martinkomitsky, @HaseProgram, @kgrechin или @Ivan-Bir проверить его.

Что было сделано:

Исправил код в соответствии с замечаниями.

2024-09-25 10:13 UTC, Ivan-Bir approved these changes
Есть некритичные замечания, если поправишь будет плюсик в карму.
Апрув ставлю

2024-09-25 10:13 UTC, Ivan-Bir commented on package.json
> +}
Пустая строка

2024-09-25 10:13 UTC, Ivan-Bir commented on nonUniqueElements.js
> +
1) Не учтено замечание про один обход массива
2) Стало менее читаемо. Давай пользоваться молодежными методами массивов в js вместо сишного синтаксиса https://learn.javascript.ru/array-methods

2024-09-25 10:13 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  if (!isValidNumber(bytes)) return false;
Не увидел в первый раз. Даже однострочные ифаки принято делать в фигурных скобках. Это делает код более стандартным, уменьшая конгинивную нагрузку разработчикам. Здесь и ниже

2024-09-25 10:13 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  const NAMES_OF_UNIT = ["B", "KB", "MB", "GB", "TB"];
Давай ещё договоримся, что если не фиксишь целиком комент, то отписывай почему сделал не так, чтобы я не открывал треды заново. Ок?

2024-09-25 10:13 UTC, Ivan-Bir commented on README.md
> -# 2024-2-VK-EDU-Frontend-N-Dedy
Этот файл не надо удалять из проекта. Зачастую это единственная документация проекта)

2024-09-25 10:13 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(1.5)).toBe("1.5 B");
Не отписал в первый раз, но обычно данные хранятся в целых байтах и по логике convertBytesToHuman(1.5) должен возвращать 1 B. Вопрос обсуждаемый, в тч с преподавателями. Оставляю на твоё усмотрение

2024-09-25 20:47 UTC, martinkomitsky commented
> Прошу @martinkomitsky, @HaseProgram, @kgrechin или @Ivan-Bir проверить его.
> 
> Что было сделано:
> 
> Исправил код в соответствии с замечаниями.

привет! повторно писать так не нужно. Это только в шапке PR. Далее уже мы видим все действия от всех участников в треде.

2024-09-25 21:05 UTC, martinkomitsky approved these changes
12!

2024-09-25 21:05 UTC, merged